export OS_NAME="archlinux"
export VM_NAME="arch"
export ISO_IMAGE="/home/tau/Storage/images/archlinux-x86_64.iso"
export DISK_IMAGE="/home/tau/Storage/images/archlinux.qcow2"
export DISK_SIZE="200G" # GB
export MEMORY="16G" # MB
export VCPUS="8"
export SHARED_DIR="/home/tau/Projects/archlinux-vm"
export SNAPSHOT_IMAGE="/home/tau/Storage/images/archlinux-snapshot.qcow2"
export SNAPSHOT_NAME="snap0"
